# Generated by Django 5.2.6 on 2025-09-20 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'text'), ('flashcard', 'flashcard'), ('list', 'list'), ('heading', 'heading')], default='text', max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('heading_level', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='knowledge.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.block')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('basic', 'basic'), ('anterior', 'anterior'), ('posterior', 'posterior'), ('doble', 'doble'), ('cloze', 'cloze'), ('multiple', 'multiple')], default='basic', max_length=16)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('theme', models.CharField(blank=True, default='', max_length=200)),
                ('difficulty', models.CharField(choices=[('muy-facil', 'muy-facil'), ('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil'), ('muy-dificil', 'muy-dificil')], default='facil', max_length=12)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='knowledge.block')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='knowledge.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('again', 'again'), ('hard', 'hard'), ('good', 'good'), ('easy', 'easy')], max_length=8)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease', models.FloatField(default=2.5)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='knowledge.flashcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['owner', 'next_review'], name='knowledge_f_owner_i_3cd92c_idx'),
        ),
    ]
