# Generated by Django 5.2.6 on 2025-09-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_block_flashcard_reviewlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
