# Generated by Django 5.2.6 on 2025-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_document_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['position', 'id']},
        ),
        migrations.RemoveField(
            model_name='block',
            name='order',
        ),
        migrations.RemoveField(
            model_name='block',
            name='parent',
        ),
        migrations.AddField(
            model_name='block',
            name='flashcard_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('anterior', 'Anterior'), ('posterior', 'Posterior'), ('doble', 'Doble'), ('cloze', 'Cloze'), ('multiple', 'Multiple')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('flashcard', 'Flashcard'), ('list', 'List'), ('heading', 'Heading')], default='text', max_length=20),
        ),
    ]
