# Generated by Django 5.2.6 on 2025-09-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_block_options_remove_block_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='block',
            name='flashcard_type',
        ),
        migrations.RemoveField(
            model_name='block',
            name='position',
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('flashcard', 'flashcard'), ('list', 'list'), ('heading', 'heading')], default='text', max_length=16),
        ),
    ]
