# Generated by Django 5.2.6 on 2025-09-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_block_options_remove_block_flashcard_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='grade',
            field=models.CharField(choices=[('again', 'again'), ('hard', 'hard'), ('good', 'good'), ('easy', 'easy'), ('skip', 'skip')], max_length=8),
        ),
    ]
