# Generated by Django 5.2.6 on 2025-09-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_alter_folder_options_folder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['position', 'id']},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='updated_at',
        ),
    ]
