# Generated by Django 5.2.6 on 2025-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_alter_folder_options_folder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('olvide', 'olvide'), ('parcialmente', 'parcialmente'), ('esfuerzo', 'esfuerzo'), ('facil', 'facil'), ('saltar', 'saltar')], default='facil', max_length=12),
        ),
    ]
