# Generated by Django 5.2.6 on 2025-09-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_alter_flashcard_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('muy-facil', 'muy-facil'), ('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil'), ('muy-dificil', 'muy-dificil')], default='facil', max_length=12),
        ),
    ]
