# Generated by Django 5.2.6 on 2025-09-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_alter_flashcard_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('olvide', 'olvide'), ('parcialmente', 'parcialmente'), ('esfuerzo', 'esfuerzo'), ('facil', 'facil'), ('saltar', 'saltar')], default='Sin registro', max_length=12),
        ),
    ]
